name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          architecture: x64
      - run: java -jar junit-platform-console-standalone-1.11.3.jar execute --class-path . --scan-class-path --include-classname EvenAndOddNumberTest